name: Check and Dispatch new commits
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check if new commits
        id: check
        run: |
          LAST_COMMITID=$(curl -s -H "Accept: application/vnd.github.VERSION.sha" https://api.github.com/repos/GoogleCloudPlatform/terraformer/commits/master)
          echo ::set-output name=IMAGE_EXIST::$(curl -s -o /dev/null -w "%{http_code}" "https://registry.hub.docker.com/v2/repositories/troissixzero/terraformer/tags/${LAST_COMMITID::7}/")
      - name: Dispatch
        if: ${{ steps.check.outputs.IMAGE_EXIST == '404' }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          event-type: buildAndPush
